// GET http://localhost:3000/

### 
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNzY3NTA4NDM3LCJleHAiOjE3Njc1MDg0NDd9.8M2_3d0c3DGMuy1-c0ELy6uwwpWs44PyMj914BQ8BWg

### 
POST http://localhost:4000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNzY3NTA4NDEyfQ.flGGR-xl3PNhxLv27ZKAqJ7xQ_YwI0qOPqvVUna87oE"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}